name: Fetch Daily Dollar Price
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # 9 AM UTC daily

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install node-fetch
      - run: node fetch-dollar.js
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

      - name: Configure Git Credentials
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@://github.com"
        shell: bash
      - run: git add prices.json && git commit -m "Update prices" || true
      - run: git push
